version: "3.2"

services:

  tf-serving:
    image: tensorflow/serving
    container_name: 'tf-serving'
    command:
      - "--rest_api_port=8501"
      - "--model_config_file=/plant-disease-prediction/models.config"
    ports:
      - "8501:8501"
    volumes:
      - ".:/plant-disease-prediction"

  server:
    container_name: 'server'
    build: ./server
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - "8000:8000"
    volumes:
      - "./server:/server"
    depends_on:
      - tf-serving